### ISSUE TITLE
Specify I2C bus

### ISSUE THREAD

**Issue by Cale** [sparkfun/Qwiic_I2C_Py#11]
I'm wondering if there's a way to specify the I2C bus that I want to work with on a system with multiple buses?

I'm working with a Libre Computer board that has multiple I2C buses. Unfortunately, the Qwiic library seems to only work with the first bus in the list. (/dev/i2c-0 vs /dev/i2c-1) Of course, my LCD is attached to the second bus in the list. Thanks.

**Comment by Cale** [comment]
For additional context, this is what the hardware looks like:

```
cale@k4hck-igate:~ $ i2cdetect -l
i2c-1	i2c       	DesignWare HDMI                 	I2C adapter
i2c-0	i2c       	Meson I2C adapter               	I2C adapter
cale@k4hck-igate:~ $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: 30 -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --                         
cale@k4hck-igate:~ $ i2cdetect -y 0
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- 72 -- -- -- -- --
```

The Qwiic library appears to be connecting to the HDMI adapter, but the LCD is on the Meson adapter.

**Comment by Cale** [comment]
As a work around I discovered that I could modify the i2c adapter number that's hard coded in https://github.com/sparkfun/Qwiic_I2C_Py/blob/master/qwiic_i2c/linux_i2c.py on line 63. Changing the adapter to 0 allowed me to access my Qwiic device on that adapter. On my system, that file was located on this path: /usr/local/lib/python3.9/dist-packages/qwiic_i2c/linux_i2c.py

Hope this helps others.

**Comment by santaimpersonator** [comment]
* I'm transferring this over to the appropriate repository.
* Since this isssue is pertaining to hardware that we currently don't [support](https://github.com/sparkfun/Qwiic_I2C_Py#supported-platforms), I will label this issue as `invalid` for now.

---
### ~For tracking purposes:~
~Feel free to add a 👍 reaction on this comment, if you need this support. Would the 50th person ping us again, so our team can revist adding support for other hardware.~

~Potential fix *(untested)*:~
``` py
def _connectToI2CBus(iBus = 1):

	try:
		import smbus2
	except Exception as ee:
		print("Error: Unable to load smbus module. Unable to continue", file=sys.stderr)
		return None

	daBus = None

	error=False

	# Connect - catch errors 

	try:
		daBus =  smbus2.SMBus(iBus)
```

**Comment by santaimpersonator** [comment]
Upon further review of the code, users can use the set/get attribution or manually declare the bus. Closing issue; please feel free to reopen.

``` py
In [1]: import qwiic
In [2]: bus = qwiic.qwiic_i2c.getI2CDriver()
In [13]: import smbus2
In [16]: bus._i2cbus = smbus2.SMBus(1)
In [18]: bus.__setattr__("_i2cbus",smbus2.SMBus(1))
```
