### ISSUE TITLE
i2c_driver.py empty functions with no actions

### ISSUE THREAD

**Issue by SahanGura** [sparkfun/Qwiic_I2C_Py#6]
This package contains required functions with description of the functionality but does not contain the code to perform the actions. i2c_driver.py  contains a whole set of empty functions. How can I update these functions to make use of this package?

**Comment by santaimpersonator** [comment]
This package is meant to be used with our Qwiic devices ([listed here](https://github.com/sparkfun/Qwiic_Py/tree/main/qwiic/drivers)) and the [supported hardware](https://github.com/sparkfun/Qwiic_I2C_Py#supported-platforms). Please, review our [documentation here](https://qwiic-i2c-py.readthedocs.io/en/latest/apiref.html).

That file is for general use (i.e. as a super class).

_*I'm going to close this issue as it is over a year old, but feel free to reopen it._
